#!/usr/bin/env python3
"""Generate audio data for the GBA build into assets/generated/audio.{c,h}.

- Music: note tables for the Game Boy channels (melody, arpeggio, bass, drums) for the
  town theme (C major, 120 BPM) and the boss theme (A minor, ~128 BPM). Same note data as the
  Godot version's tools/generer_musique.py, expressed in semitones from A4.
- SFX: 8-bit signed PCM at 11025 Hz, resampled from the Godot WAVs, played on DirectSound.
"""
import struct
import wave
from pathlib import Path

RACINE = Path(__file__).resolve().parent.parent
SORTIE = RACINE / "assets" / "generated"
SFX_RATE = 11025

# ---------------------------------------------------------------- note data (semitones from A4)
C, D, E, F, G, A, B, C5, D5, E5, G5 = -9, -7, -5, -4, -2, 0, 2, 3, 5, 7, 10
VILLE = dict(
    frames_per_eighth=15,   # 120 BPM at 60 Hz
    progression=[C, C, G, G, A, A, F, G],
    arpeges={
        C: [C, E, G, C5, E5, C5, G, E],
        G: [G - 12, B - 12, D, G, B, G, D, B - 12],
        A: [A - 12, C, E, A, C5, A, E, C],
        F: [F - 12, A - 12, C, F, A, F, C, A - 12],
    },
    melodie=[
        [E5, None, D5, C5, None, E5, G5, None],
        [E5, D5, None, C5, D5, None, G, None],
        [D5, None, B, G, None, B, D5, None],
        [D5, B, None, G, A, None, B, None],
        [C5, None, E5, A, None, C5, E5, None],
        [E5, C5, None, A, C5, None, E5, None],
        [F, A, C5, None, A, C5, F, None],
        [G, B, D5, None, B, D5, G5, None],
    ],
)
Am, Fm_, Dm, Em = A - 12, F - 12, D - 12, E - 12
GS4, F5, GS5 = -1, 8, 11
BOSS = dict(
    frames_per_eighth=14,   # ~128 BPM
    progression=[Am, Am, Fm_, Fm_, Dm, Dm, Em, Em],
    arpeges={
        Am: [Am, C, E, A, C5, A, E, C],
        Fm_: [Fm_, A - 12, C, F, A, F, C, A - 12],
        Dm: [Dm, F - 12, A - 12, D, F, D, A - 12, F - 12],
        Em: [Em, GS4 - 12, B - 12, E, GS4, E, B - 12, GS4 - 12],
    },
    melodie=[
        [A, None, C5, E5, None, C5, A, None],
        [E5, None, F5, E5, C5, None, A, None],
        [F, A, C5, None, F5, None, C5, None],
        [C5, A, F, None, E, None, F, None],
        [D, F, A, None, D5, None, A, None],
        [F, D, None, F, A, None, C5, None],
        [E, GS4, B, None, E5, None, GS5, None],
        [E5, None, D5, None, B, None, GS4, None],
    ],
)
REST = 127  # "no note" marker in the C tables


def gb_freq_register(semitone):
    """Game Boy square/wave frequency register value for a semitone offset from A4."""
    f = 440.0 * 2 ** (semitone / 12.0)
    return max(0, min(2047, round(2048 - 131072.0 / f)))


def tables(ens):
    melodie, arp, basse = [], [], []
    for mesure in range(8):
        racine = ens["progression"][mesure]
        melodie += [REST if n is None else n for n in ens["melodie"][mesure]]
        arp += ens["arpeges"][racine]
        for temps in range(4):
            basse.append(racine - 12 if temps % 2 == 0 else racine - 12 + 7)
    return melodie, arp, basse


# ---------------------------------------------------------------- SFX
def charger_wav_8bit(chemin, rate):
    with wave.open(str(chemin), "rb") as w:
        n, sr, sw, ch = w.getnframes(), w.getframerate(), w.getsampwidth(), w.getnchannels()
        data = w.readframes(n)
    assert sw == 2 and ch == 1, chemin
    samples = struct.unpack("<%dh" % n, data)
    out = bytearray()
    pos = 0.0
    pas = sr / rate
    while int(pos) < n:
        out.append((samples[int(pos)] >> 8) & 0xFF)  # 16-bit -> signed 8-bit (two's complement)
        pos += pas
    while len(out) % 4:
        out.append(0)
    return bytes(out)


def c_array(nom, octets, type_c="const signed char", par_ligne=32):
    lignes = [f"{type_c} {nom}[{len(octets)}] __attribute__((aligned(4))) = {{"]
    for i in range(0, len(octets), par_ligne):
        lignes.append("    " + ", ".join(str(struct.unpack('b', bytes([b]))[0]) for b in octets[i:i + par_ligne]) + ",")
    lignes.append("};")
    return "\n".join(lignes)


def main():
    SORTIE.mkdir(parents=True, exist_ok=True)
    c = ['#include "audio_data.h"', ""]
    h = ["#pragma once", "// Generated by tools/gen_audio.py — do not edit.", "",
         f"#define SFX_RATE {SFX_RATE}", f"#define NOTE_REST {REST}", "#define MUSIC_STEPS 64", "#define MUSIC_BEATS 32", ""]
    # GB frequency registers for semitones -36..+35 (A1..G#7), index = semitone + 36
    regs = [gb_freq_register(n) for n in range(-36, 36)]
    c.append("const unsigned short gb_note_regs[72] = {" + ", ".join(str(v) for v in regs) + "};")
    h.append("extern const unsigned short gb_note_regs[72];  // index = semitone + 36")
    h.append("#define NOTE_REG(semi) gb_note_regs[(semi) + 36]")
    for nom, ens in (("town", VILLE), ("boss", BOSS)):
        melodie, arp, basse = tables(ens)
        c.append(f"const signed char {nom}_melody[64] = {{" + ", ".join(map(str, melodie)) + "};")
        c.append(f"const signed char {nom}_arp[64] = {{" + ", ".join(map(str, arp)) + "};")
        c.append(f"const signed char {nom}_bass[32] = {{" + ", ".join(map(str, basse)) + "};")
        h += [f"extern const signed char {nom}_melody[64];", f"extern const signed char {nom}_arp[64];",
              f"extern const signed char {nom}_bass[32];", f"#define {nom.upper()}_FRAMES_PER_EIGHTH {ens['frames_per_eighth']}"]
    for nom in ("vomi", "pickup", "mort", "pret", "boss", "victoire"):
        data = charger_wav_8bit(RACINE / "assets" / f"{nom}.wav", SFX_RATE)
        c.append(c_array(f"sfx_{nom}", data))
        h.append(f"extern const signed char sfx_{nom}[{len(data)}];")
        h.append(f"#define SFX_{nom.upper()}_LEN {len(data)}")
        print(f"sfx_{nom}: {len(data)} bytes")
    (SORTIE / "audio_data.c").write_text("\n".join(c) + "\n")
    (SORTIE / "audio_data.h").write_text("\n".join(h) + "\n")


if __name__ == "__main__":
    main()
